import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/auth';
import { CicloEscolar, CicloEscolarService } from '../../core/services/ciclo-escolar.service';
import { ConfiguracionService } from '../../core/services/configuracion.service';
import { EstructuraAcademicaError, EstructuraAcademicaService, Grado, GradoInput, Jornada, JornadaInput, Seccion, SeccionInput } from '../../core/services/estructura-academica.service';

type Tab = 'grados' | 'jornadas' | 'secciones';

@Component({ selector: 'app-configuracion-estructura-academica', standalone: true, imports: [CommonModule, FormsModule], templateUrl: './configuracion-estructura-academica.html', styleUrl: './configuracion-estructura-academica.css' })
export class ConfiguracionEstructuraAcademica implements OnInit {
  tab: Tab = 'grados'; grados: Grado[] = []; jornadas: Jornada[] = []; ciclos: CicloEscolar[] = []; secciones: Seccion[] = [];
  cicloId = ''; institucionId?: string; cargando = false; guardando = false; mensaje = ''; esError = false;
  mostrarGrado = false; mostrarJornada = false; mostrarSeccion = false; editandoGrado: Grado | null = null; editandoJornada: Jornada | null = null; editandoSeccion: Seccion | null = null;
  gradoForm: GradoInput = { nombre: '', orden: 0 }; jornadaForm: JornadaInput = { nombre: '' }; seccionForm: SeccionInput = this.seccionVacia();
  constructor(private readonly router: Router, private readonly auth: AuthService, private readonly configuracion: ConfiguracionService, private readonly ciclosService: CicloEscolarService, private readonly service: EstructuraAcademicaService, private readonly cdr: ChangeDetectorRef) {}
  get puedeVerGrados() { return this.auth.tienePermiso('configuracion.grados.ver'); } get puedeCrearGrados() { return this.auth.tienePermiso('configuracion.grados.crear'); } get puedeEditarGrados() { return this.auth.tienePermiso('configuracion.grados.editar'); } get puedeDesactivarGrados() { return this.auth.tienePermiso('configuracion.grados.desactivar'); }
  get puedeVerJornadas() { return this.auth.tienePermiso('configuracion.jornadas.ver'); } get puedeCrearJornadas() { return this.auth.tienePermiso('configuracion.jornadas.crear'); } get puedeEditarJornadas() { return this.auth.tienePermiso('configuracion.jornadas.editar'); } get puedeDesactivarJornadas() { return this.auth.tienePermiso('configuracion.jornadas.desactivar'); }
  get puedeVerSecciones() { return this.auth.tienePermiso('configuracion.secciones.ver'); } get puedeCrearSecciones() { return this.auth.tienePermiso('configuracion.secciones.crear'); } get puedeEditarSecciones() { return this.auth.tienePermiso('configuracion.secciones.editar'); } get puedeDesactivarSecciones() { return this.auth.tienePermiso('configuracion.secciones.desactivar'); }
  get ciclosActivos() { return this.ciclos.filter(ciclo => ciclo.activo); } get gradosActivos() { return this.grados.filter(grado => grado.activo); } get jornadasActivas() { return this.jornadas.filter(jornada => jornada.activo); }
  async ngOnInit() { await this.cargar(); }
  async cargar() { this.cargando = true; this.mensaje = ''; try { const contexto = await this.configuracion.obtenerContexto(); this.institucionId = contexto.institucion?.id; if (contexto.multiplesInstituciones && !this.institucionId) throw new EstructuraAcademicaError('Seleccione una institución para continuar.', 'SM003'); const [grados, jornadas, ciclos] = await Promise.all([this.service.listarGrados(this.institucionId), this.service.listarJornadas(this.institucionId), this.ciclosService.listar(this.institucionId)]); this.grados = grados; this.jornadas = jornadas; this.ciclos = ciclos; if (this.cicloId) await this.cargarSecciones(); } catch (error) { this.error(error); } finally { this.cargando = false; this.cdr.detectChanges(); } }
  seleccionarTab(tab: Tab) { this.tab = tab; this.cdr.detectChanges(); }
  async seleccionarCiclo() { await this.cargarSecciones(); }
  async cargarSecciones() { if (!this.cicloId) { this.secciones = []; return; } this.cargando = true; try { this.secciones = await this.service.listarSecciones(this.cicloId, this.institucionId); } catch (error) { this.error(error); } finally { this.cargando = false; this.cdr.detectChanges(); } }
  abrirGrado(grado?: Grado) { this.editandoGrado = grado ?? null; this.gradoForm = grado ? { nombre: grado.nombre, orden: grado.orden } : { nombre: '', orden: 0 }; this.mostrarGrado = true; }
  abrirJornada(jornada?: Jornada) { this.editandoJornada = jornada ?? null; this.jornadaForm = { nombre: jornada?.nombre ?? '' }; this.mostrarJornada = true; }
  abrirSeccion(seccion?: Seccion) { if (!this.cicloId) return; this.editandoSeccion = seccion ?? null; this.seccionForm = seccion ? { cicloId: seccion.cicloId, gradoId: seccion.gradoId, jornadaId: seccion.jornadaId, nombre: seccion.nombre, cupo: seccion.cupo } : { ...this.seccionVacia(), cicloId: this.cicloId }; this.mostrarSeccion = true; }
  async guardarGrado() { if (!this.gradoForm.nombre.trim() || this.gradoForm.orden === null || this.gradoForm.orden < 0) return this.error(new EstructuraAcademicaError('Nombre obligatorio y orden mayor o igual a cero.', '22023')); await this.guardar(async () => { if (this.editandoGrado) await this.service.actualizarGrado(this.editandoGrado.id, this.gradoForm, this.institucionId); else await this.service.crearGrado(this.gradoForm, this.institucionId); this.mostrarGrado = false; await this.cargar(); }, 'Grado guardado correctamente.'); }
  async guardarJornada() { if (!this.jornadaForm.nombre.trim()) return this.error(new EstructuraAcademicaError('El nombre de la jornada es obligatorio.', '22023')); await this.guardar(async () => { if (this.editandoJornada) await this.service.actualizarJornada(this.editandoJornada.id, this.jornadaForm, this.institucionId); else await this.service.crearJornada(this.jornadaForm, this.institucionId); this.mostrarJornada = false; await this.cargar(); }, 'Jornada guardada correctamente.'); }
  async guardarSeccion() { const form = this.seccionForm; if (!form.cicloId || !form.gradoId || !form.nombre.trim() || (form.cupo !== null && (!Number.isInteger(form.cupo) || form.cupo <= 0))) return this.error(new EstructuraAcademicaError('Ciclo, grado y nombre son obligatorios. El cupo debe ser un entero positivo.', '22023')); await this.guardar(async () => { if (this.editandoSeccion) await this.service.actualizarSeccion(this.editandoSeccion.id, form, this.institucionId); else await this.service.crearSeccion(form, this.institucionId); this.mostrarSeccion = false; this.cicloId = form.cicloId; await this.cargarSecciones(); }, 'Sección guardada correctamente.'); }
  async cambiarGrado(grado: Grado) { await this.cambiar(grado.activo, () => grado.activo ? this.service.desactivarGrado(grado.id, this.institucionId) : this.service.reactivarGrado(grado.id, this.institucionId), () => this.cargar()); }
  async cambiarJornada(jornada: Jornada) { await this.cambiar(jornada.activo, () => jornada.activo ? this.service.desactivarJornada(jornada.id, this.institucionId) : this.service.reactivarJornada(jornada.id, this.institucionId), () => this.cargar()); }
  async cambiarSeccion(seccion: Seccion) { if (seccion.activo) { const motivo = window.prompt('Motivo de desactivación:')?.trim(); if (!motivo) return this.error(new EstructuraAcademicaError('El motivo de desactivación es obligatorio.', '22023')); await this.guardar(async () => { await this.service.desactivarSeccion(seccion.id, motivo, this.institucionId); await this.cargarSecciones(); }, 'Sección desactivada correctamente.'); } else await this.guardar(async () => { await this.service.reactivarSeccion(seccion.id, this.institucionId); await this.cargarSecciones(); }, 'Sección reactivada correctamente.'); }
  cancelar() { if (!this.guardando) { this.mostrarGrado = this.mostrarJornada = this.mostrarSeccion = false; } }
  volver() { void this.router.navigate(['/configuracion']); }
  private seccionVacia(): SeccionInput { return { cicloId: '', gradoId: '', jornadaId: null, nombre: '', cupo: null }; }
  private async guardar(action: () => Promise<void>, message: string) { if (this.guardando) return; this.guardando = true; this.mensaje = ''; try { await action(); this.mensaje = message; this.esError = false; } catch (error) { this.error(error); } finally { this.guardando = false; this.cdr.detectChanges(); } }
  private async cambiar(activo: boolean, action: () => Promise<void>, reload: () => Promise<void>) { await this.guardar(async () => { await action(); await reload(); }, activo ? 'Registro desactivado correctamente.' : 'Registro reactivado correctamente.'); }
  private error(error: unknown) { this.mensaje = error instanceof EstructuraAcademicaError ? error.message : 'No se pudo completar la operación.'; this.esError = true; this.cdr.detectChanges(); return false; }
}